name: Build c-toxcore
on:
  push:
    paths:
      - '**'
      - '!**.md'
  pull_request:
    paths:
      - '**'
      - '!**.md'
jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install deps
        run: |
          sudo apt-get install -y --no-install-recommends \
          ninja-build \
          && sudo rm -rf /var/lib/apt/lists/*
      - name: build
        run: |
          cmake -B_build -H. -GNinja \
            -DCMAKE_C_FLAGS="$C_FLAGS" \
            -DCMAKE_CXX_FLAGS="$CXX_FLAGS" \
            -DCMAKE_EXE_LINKER_FLAGS="$LD_FLAGS" \
            -DCMAKE_SHARED_LINKER_FLAGS="$LD_FLAGS" \
            -DCMAKE_INSTALL_PREFIX:PATH="$PWD/_install" \
            -DMIN_LOGGER_LEVEL=TRACE \
            -DMUST_BUILD_TOXAV=ON \
            -DNON_HERMETIC_TESTS=ON \
            -DSTRICT_ABI=ON \
            -DTEST_TIMEOUT_SECONDS=120 \
            -DUSE_IPV6=OFF \
            -DAUTOTEST=ON

            cmake --build _build --parallel "$(nproc)" --target install -- -k 0
